"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
require("dotenv/config");
const config_1 = require("prisma/config");
exports.default = (0, config_1.defineConfig)({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'prisma/migrations',
        seed: 'ts-node ./src/temp/seed.ts',
    },
    datasource: {
        url: process.env.POSTGRESQL_DATABASE_URL,
        shadowDatabaseUrl: process.env.POSTGRESQL_SHADOW_DATABASE_URL,
    },
});
//# sourceMappingURL=prisma.config.js.map