export const ErrorCode = {
  BLOCKED_USER: 'BLOCKED_USER',
  INVALID_PARAM: 'INVALID_PARAM',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  INVALID_SESSION: 'INVALID_SESSION',
  EMAIL_VERIFICATION_REQUIRED: 'EMAIL_VERIFICATION_REQUIRED',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
